### ISSUE TITLE
Umlauts are not working

### ISSUE THREAD

**Issue by MichaelMerkel** [salass00/smb2fs#2]
I create a Direcory with Umlauts (german) on my NAS drive via the WebUI of the NAS
Name: "AllesMögliche".

When listing the directory it shows:

5.HomeNAS:> list
MediaToolbox_Profile_Main_02.01.2018       4892 ----rwed 02-Jan-18 10:12:15
Partitionen1.png             117910 ----rwed 21-Okt-15 22:18:10
Partitionen.txt                 989 ----rwed 13-Nov-12 20:03:26
Partitionen3.png             153038 ----rwed 21-Okt-15 22:19:02
**AllesMÃ¶gliche**                Verz. ----rwed Heute     17:37:19
...

This makes it impossible to copy my backup tot he NAS currently.

I tried olaf's smbfs and that one works fine in this regard.

thanks and regards
Michael

**Comment by salass00** [comment]
This is not a smb2-handler specific issue, but a quite complex filesysbox one that should be solved with the latest version 54.12 filesysbox.library which has just been released to beta testers.

Because not all UTF-8 (unicode) characters can be represented in 8-bit local charsets I had to implement an escaping system for those characters so that the conversion can happen both ways and the original UTF-8 names can be obtained.
